// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjCL0pc_fi7lRmHBlm-v8OTfjJRAmnvt0',
    appId: '1:456330560507:web:a6969170590aa78a0dc15e',
    messagingSenderId: '456330560507',
    projectId: 'e-wallet-5e5dd',
    authDomain: 'e-wallet-5e5dd.firebaseapp.com',
    storageBucket: 'e-wallet-5e5dd.firebasestorage.app',
    measurementId: 'G-2Z934BF90J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAogYw9zwyuQn9-5HmvsfZBY0L5_1qxi9I',
    appId: '1:456330560507:android:54930f4f6de240c20dc15e',
    messagingSenderId: '456330560507',
    projectId: 'e-wallet-5e5dd',
    storageBucket: 'e-wallet-5e5dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkxNVo2sZXsH_VpqsGvVu1rpkgcuKRnGo',
    appId: '1:456330560507:ios:4a12f694f225ddb60dc15e',
    messagingSenderId: '456330560507',
    projectId: 'e-wallet-5e5dd',
    storageBucket: 'e-wallet-5e5dd.firebasestorage.app',
    iosBundleId: 'com.example.eWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkxNVo2sZXsH_VpqsGvVu1rpkgcuKRnGo',
    appId: '1:456330560507:ios:4a12f694f225ddb60dc15e',
    messagingSenderId: '456330560507',
    projectId: 'e-wallet-5e5dd',
    storageBucket: 'e-wallet-5e5dd.firebasestorage.app',
    iosBundleId: 'com.example.eWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjCL0pc_fi7lRmHBlm-v8OTfjJRAmnvt0',
    appId: '1:456330560507:web:6c2bbf7dee78384d0dc15e',
    messagingSenderId: '456330560507',
    projectId: 'e-wallet-5e5dd',
    authDomain: 'e-wallet-5e5dd.firebaseapp.com',
    storageBucket: 'e-wallet-5e5dd.firebasestorage.app',
    measurementId: 'G-B7DHJ4ZV3M',
  );
}
